name: backend Actions

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Deploy Docker backend and db
      run: |
        cd /home/prueba/services/reservac/backend/
        git pull https://github.com/Etvulk/reservac-backend.git
        docker compose up --build -d
