name: backend Actions

on:
  push:
    branches: [ "master" ]
  
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: prueba
      run: |
        cd ~/services/reservac/backend/
        docker compose up --build -d
